#
# This rake file launches the unit tests in the
# current directory.  This is accomplished by directing
# a browser to the JsUnit test runner.
#

require "#{File.join(File.dirname(__FILE__), "..", "test_helper.rb")}"

# The lists of tests to run from the current directory.
#
# Note: setupTest.html can be used to ensure that
#       the environment is setup correctly.
#
UNIT_TESTS=[
	'util.html',
	'thumbnail.html']

# Used to create relative URLS.
UNIT_TESTBASE = File.join(".", "..", "..", "unit")

task :default do
  runner = JsUnitTestRunner.new
  UNIT_TESTS.each do |test|
    puts "Starting #{test}"
    runner.execute_test(File.join(UNIT_TESTBASE, test))
  end
end
